const EVENTS = {
    START_GAME: 'START_GAME',
    FINISH_GAME: 'FINISH_GAME',
    CONTROLS_PRESSED: 'CONTROLS_PRESSED',
    GAME_STATE_CHANGED: 'GAME_STATE_CHANGED',
    CLOSE_GAME: 'CLOSE GAME',
};
export default EVENTS;
